# Generated by Django 4.2.4 on 2023-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_alternativa_questao_questionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='letra',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='questao',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
