# Generated by Django 4.2.4 on 2023-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_alternativa_letra_alter_questao_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='letra',
        ),
    ]
