# Generated by Django 4.2.4 on 2023-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_remove_alternativa_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=200),
        ),
    ]
