# Generated by Django 4.2.4 on 2023-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0005_alter_alternativa_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
