# Generated by Django 4.2.4 on 2023-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0009_remove_alternativa_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
