# Generated by Django 4.2.4 on 2023-08-31 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0012_score_delete_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacao', models.TextField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.score')),
            ],
        ),
    ]
