# Generated by Django 4.2.4 on 2023-09-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0016_rename_nivel_nivel_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacao', models.TextField(default='')),
                ('pontuacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='questionario',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='explicacao',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Explicacao',
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
        migrations.AddField(
            model_name='score',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario'),
        ),
    ]
