# Generated by Django 4.2.4 on 2023-09-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0017_score_remove_nivel_questionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.CharField(max_length=200)),
                ('pontuacao1', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questao1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(max_length=200)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario')),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='alternativa1',
            name='questao1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questao1'),
        ),
    ]
