# Generated by Django 4.2.4 on 2023-09-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0018_alternativa1_questao1_delete_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('pontuacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='nivel',
            old_name='titulo1',
            new_name='titulo',
        ),
        migrations.RenameModel(
            old_name='Questao1',
            new_name='Nivel',
        ),
        migrations.DeleteModel(
            name='Alternativa1',
        ),
        migrations.AddField(
            model_name='explicacao',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.nivel'),
        ),
    ]
