# Generated by Django 4.2.4 on 2023-09-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0019_explicacao_rename_titulo1_nivel_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel',
            old_name='titulo1',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='explicacao',
            name='nivel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questionario.nivel'),
            preserve_default=False,
        ),
    ]
