# Generated by Django 4.2.4 on 2023-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0021_remove_alternativa_pontuacao_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Pontuacao',
        ),
    ]
