# Generated by Django 4.2.4 on 2023-09-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0022_alternativa_pontuacao_delete_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='imagem',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
